-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ROLES & TYPES
CREATE TYPE user_role AS ENUM ('admin', 'farmer');
CREATE TYPE crop_type AS ENUM ('vegetable', 'aquaculture');
CREATE TYPE crop_status AS ENUM ('planned', 'active', 'harvested');
CREATE TYPE device_type AS ENUM ('soil_moisture', 'water_quality', 'climate_station');
CREATE TYPE log_type AS ENUM ('feed_input', 'mortality', 'labor_hours', 'electricity_usage', 'fertilizer_application', 'pest_incidence', 'water_usage', 'biomass_check');
CREATE TYPE quality_grade AS ENUM ('A', 'B', 'C');
CREATE TYPE expense_category AS ENUM ('seeds', 'feed', 'labor', 'transport', 'maintenance', 'irrigation', 'pest_control');

-- PROFILES
CREATE TABLE profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    phone_number TEXT,
    role user_role DEFAULT 'farmer',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- FARMS
CREATE TABLE farms (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    owner_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    location TEXT,
    total_area NUMERIC, -- measured in Bighas
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- CROP CYCLES
CREATE TABLE crop_cycles (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    farm_id UUID REFERENCES farms(id) ON DELETE CASCADE NOT NULL,
    crop_name TEXT NOT NULL,
    crop_type crop_type NOT NULL,
    status crop_status DEFAULT 'planned',
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- IOT DEVICES
CREATE TABLE iot_devices (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    farm_id UUID REFERENCES farms(id) ON DELETE CASCADE NOT NULL,
    device_name TEXT NOT NULL,
    device_type device_type NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- IOT READINGS (High Volume)
CREATE TABLE iot_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id UUID REFERENCES iot_devices(id) ON DELETE CASCADE NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    soil_moisture NUMERIC, -- %
    ph_level NUMERIC,
    npk_nitrogen NUMERIC,
    npk_phosphorus NUMERIC,
    npk_potassium NUMERIC,
    dissolved_oxygen NUMERIC, -- mg/L
    ammonia NUMERIC, -- mg/L
    nitrate NUMERIC, -- mg/L
    salinity NUMERIC, -- ppt
    temperature NUMERIC, -- Celsius
    humidity NUMERIC -- %
);
-- Index for faster time-series queries
CREATE INDEX idx_iot_readings_device_time ON iot_readings(device_id, recorded_at DESC);

-- OPERATIONAL LOGS
CREATE TABLE operational_logs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    farm_id UUID REFERENCES farms(id) ON DELETE CASCADE NOT NULL,
    log_date DATE DEFAULT CURRENT_DATE, -- Corrected from UNITE to DATE
    log_type log_type NOT NULL,
    quantity NUMERIC, -- General quantity field (kg, count, hours, etc.)
    unit TEXT, -- e.g., 'kg', 'hours', 'count'
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- HARVESTS
CREATE TABLE harvests (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    crop_cycle_id UUID REFERENCES crop_cycles(id) ON DELETE CASCADE NOT NULL,
    harvest_date DATE DEFAULT CURRENT_DATE,
    quantity_kg NUMERIC NOT NULL,
    wastage_kg NUMERIC DEFAULT 0,
    quality_grade quality_grade,
    revenue_realized NUMERIC DEFAULT 0,
    market_price_per_kg NUMERIC DEFAULT 0,
    sale_price_per_kg NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- EXPENSES
CREATE TABLE expenses (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    farm_id UUID REFERENCES farms(id) ON DELETE CASCADE NOT NULL,
    expense_date DATE DEFAULT CURRENT_DATE,
    category expense_category NOT NULL,
    amount NUMERIC NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- TRIGGER FOR UPDATED_AT
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_profiles_modtime BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_farms_modtime BEFORE UPDATE ON farms FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_crop_cycles_modtime BEFORE UPDATE ON crop_cycles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_iot_devices_modtime BEFORE UPDATE ON iot_devices FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_operational_logs_modtime BEFORE UPDATE ON operational_logs FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_harvests_modtime BEFORE UPDATE ON harvests FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_expenses_modtime BEFORE UPDATE ON expenses FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ROW LEVEL SECURITY (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE farms ENABLE ROW LEVEL SECURITY;
ALTER TABLE crop_cycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE iot_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE iot_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE operational_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE harvests ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

-- POLICIES

-- Helper function to check if user is admin
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Profiles: 
-- Users can read/update their own profile.
-- Admins can read/update all profiles.
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING ( auth.uid() = id );
CREATE POLICY "Admins can view all profiles" ON profiles FOR SELECT USING ( is_admin() );
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING ( auth.uid() = id );
CREATE POLICY "Admins can update all profiles" ON profiles FOR UPDATE USING ( is_admin() );
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK ( auth.uid() = id );

-- Farms:
-- Farmers can view/edit their own farms.
-- Admins can view/edit all farms.
CREATE POLICY "Farmers can view own farms" ON farms FOR SELECT USING ( auth.uid() = owner_id );
CREATE POLICY "Admins can view all farms" ON farms FOR SELECT USING ( is_admin() );
CREATE POLICY "Farmers can update own farms" ON farms FOR UPDATE USING ( auth.uid() = owner_id );
CREATE POLICY "Admins can update all farms" ON farms FOR UPDATE USING ( is_admin() );
CREATE POLICY "Farmers can insert own farms" ON farms FOR INSERT WITH CHECK ( auth.uid() = owner_id );
CREATE POLICY "Admins can insert farms" ON farms FOR INSERT WITH CHECK ( is_admin() );

-- General Policy Template for related tables (crop_cycles, iot_devices, operational_logs, expenses)
-- Accessible if the user owns the related farm OR is admin.

-- Crop Cycles
CREATE POLICY "Farmers can view own crop cycles" ON crop_cycles FOR SELECT USING (
    EXISTS (SELECT 1 FROM farms WHERE farms.id = crop_cycles.farm_id AND farms.owner_id = auth.uid())
);
CREATE POLICY "Admins can view all crop cycles" ON crop_cycles FOR SELECT USING ( is_admin() );
CREATE POLICY "Farmers can manage own crop cycles" ON crop_cycles FOR ALL USING (
    EXISTS (SELECT 1 FROM farms WHERE farms.id = crop_cycles.farm_id AND farms.owner_id = auth.uid())
);
CREATE POLICY "Admins can manage all crop cycles" ON crop_cycles FOR ALL USING ( is_admin() );

-- IoT Devices
CREATE POLICY "Farmers can view own devices" ON iot_devices FOR SELECT USING (
    EXISTS (SELECT 1 FROM farms WHERE farms.id = iot_devices.farm_id AND farms.owner_id = auth.uid())
);
CREATE POLICY "Admins can view all devices" ON iot_devices FOR SELECT USING ( is_admin() );
-- Assumption: Only Admins might add devices? Or farmers too? Assuming farmers can manage for now.
CREATE POLICY "Farmers can manage own devices" ON iot_devices FOR ALL USING (
    EXISTS (SELECT 1 FROM farms WHERE farms.id = iot_devices.farm_id AND farms.owner_id = auth.uid())
);
CREATE POLICY "Admins can manage all devices" ON iot_devices FOR ALL USING ( is_admin() );

-- IoT Readings
-- Farmers can view readings from their devices.
CREATE POLICY "Farmers can view own readings" ON iot_readings FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM iot_devices 
        JOIN farms ON iot_devices.farm_id = farms.id
        WHERE iot_devices.id = iot_readings.device_id AND farms.owner_id = auth.uid()
    )
);
CREATE POLICY "Admins can view all readings" ON iot_readings FOR SELECT USING ( is_admin() );
-- Readings usually inserted by system/IoT service key, but if manual:
CREATE POLICY "Farmers can insert readings" ON iot_readings FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM iot_devices 
        JOIN farms ON iot_devices.farm_id = farms.id
        WHERE iot_devices.id = iot_readings.device_id AND farms.owner_id = auth.uid()
    )
);

-- Operational Logs
CREATE POLICY "Farmers can view own logs" ON operational_logs FOR SELECT USING (
    EXISTS (SELECT 1 FROM farms WHERE farms.id = operational_logs.farm_id AND farms.owner_id = auth.uid())
);
CREATE POLICY "Admins can view all logs" ON operational_logs FOR SELECT USING ( is_admin() );
CREATE POLICY "Farmers can manage own logs" ON operational_logs FOR ALL USING (
    EXISTS (SELECT 1 FROM farms WHERE farms.id = operational_logs.farm_id AND farms.owner_id = auth.uid())
);
CREATE POLICY "Admins can manage all logs" ON operational_logs FOR ALL USING ( is_admin() );

-- Harvests
-- Harvests link to Crop Cycles, not directly to Farms, so we join through Crop Cycles -> Farms
CREATE POLICY "Farmers can view own harvests" ON harvests FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM crop_cycles
        JOIN farms ON crop_cycles.farm_id = farms.id
        WHERE crop_cycles.id = harvests.crop_cycle_id AND farms.owner_id = auth.uid()
    )
);
CREATE POLICY "Admins can view all harvests" ON harvests FOR SELECT USING ( is_admin() );
CREATE POLICY "Farmers can manage own harvests" ON harvests FOR ALL USING (
    EXISTS (
        SELECT 1 FROM crop_cycles
        JOIN farms ON crop_cycles.farm_id = farms.id
        WHERE crop_cycles.id = harvests.crop_cycle_id AND farms.owner_id = auth.uid()
    )
);
CREATE POLICY "Admins can manage all harvests" ON harvests FOR ALL USING ( is_admin() );

-- Expenses
CREATE POLICY "Farmers can view own expenses" ON expenses FOR SELECT USING (
    EXISTS (SELECT 1 FROM farms WHERE farms.id = expenses.farm_id AND farms.owner_id = auth.uid())
);
CREATE POLICY "Admins can view all expenses" ON expenses FOR SELECT USING ( is_admin() );
CREATE POLICY "Farmers can manage own expenses" ON expenses FOR ALL USING (
    EXISTS (SELECT 1 FROM farms WHERE farms.id = expenses.farm_id AND farms.owner_id = auth.uid())
);
CREATE POLICY "Admins can manage all expenses" ON expenses FOR ALL USING ( is_admin() );
